<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="ClosedXML" Version="0.105.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Facet" Version="6.6.8" />
    <PackageVersion Include="Facet.Extensions.EFCore" Version="6.6.8" />
    <PackageVersion Include="Facet.Mapping" Version="6.6.8" />
    <PackageVersion Include="FastEndpoints" Version="8.1.0" />
    <PackageVersion Include="FastEndpoints.Generator" Version="8.1.0" />
    <PackageVersion Include="FastEndpoints.Security" Version="8.1.0" />
    <PackageVersion Include="FastEndpoints.Swagger" Version="8.1.0" />
    <PackageVersion Include="FastEndpoints.Testing" Version="8.1.0" />
    <PackageVersion Include="Humanizer.Core" Version="3.0.10" />
    <PackageVersion Include="Humanizer.Core.ru" Version="3.0.10" />
    <PackageVersion Include="Ical.Net" Version="5.2.3" />
    <PackageVersion Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageVersion Include="Otp.NET" Version="1.4.1" />
    <PackageVersion Include="QRCoder" Version="1.8.0" />
    <PackageVersion Include="Quartz" Version="3.18.1" />
    <PackageVersion Include="Quartz.AspNetCore" Version="3.18.1" />
    <PackageVersion Include="Quartz.Serialization.SystemTextJson" Version="3.18.1" />
    <PackageVersion Include="Serilog" Version="4.3.1" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="SerilogTracing.Expressions" Version="2.4.0" />
    <PackageVersion Include="SerilogTracing.Instrumentation.AspNetCore" Version="2.4.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="SixLabors.Fonts" Version="[2.1.3]" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="[3.1.11]" />
    <PackageVersion Include="SixLabors.ImageSharp.Drawing" Version="[2.1.7]" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.14.0" />
    <PackageVersion Include="UaDetector" Version="5.2.0" />
    <PackageVersion Include="Ulid" Version="1.4.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
</Project>
