// <auto-generated />
using System;
using MelodyTrack.Backend.Data;
using MelodyTrack.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MelodyTrack.Backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251016195209_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.InviteCode", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Code")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<byte[]>("RoleId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.RecoveryCode", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("WasUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RecoveryCodes");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Role", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 153, 237, 189, 136, 239, 85, 185, 220, 69, 200, 138, 71, 160, 55, 244 },
                            DisplayName = "Суперпользователь",
                            RoleName = 0
                        },
                        new
                        {
                            Id = new byte[] { 1, 153, 237, 189, 164, 92, 201, 142, 60, 167, 216, 236, 125, 205, 69, 213 },
                            DisplayName = "Администратор",
                            RoleName = 1
                        },
                        new
                        {
                            Id = new byte[] { 1, 153, 237, 189, 179, 9, 105, 35, 34, 182, 33, 139, 189, 171, 222, 9 },
                            DisplayName = "Пользователь",
                            RoleName = 2
                        });
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RoleId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.InviteCode", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.RecoveryCode", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.User", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
