// <auto-generated />
using System;
using MelodyTrack.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MelodyTrack.Backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625000100_RemoveUnusedClientPortalStoredToken")]
    partial class RemoveUnusedClientPortalStoredToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Appointment", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ClientId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CourseThemeId")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LessonNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<byte[]>("ProviderId")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("RecurringRuleId")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ServiceId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CourseThemeId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RecurringRuleId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.AppointmentRecurrenceRule", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ClientId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ProviderId")
                        .HasColumnType("bytea");

                    b.Property<int?>("RecurrencePattern")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RecurrenceTypeId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ServiceId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RecurrenceTypeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("RecurrenceRules");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.AuditLog", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("ActorUserId")
                        .HasColumnType("bytea");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Client", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ContactsId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("SourceId")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ContactsId");

                    b.HasIndex("SourceId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.ClientContacts", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Telegram")
                        .HasColumnType("text");

                    b.Property<string>("Vk")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClientContacts");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.ClientPortalLoginLink", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("PinCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PinSetAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ClientPortalLoginLinks");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.ClientSource", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ClientSources");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Course", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseBlock", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CourseId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Order")
                        .IsUnique();

                    b.ToTable("CourseBlocks");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseBranch", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("BlockId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BlockId", "Order")
                        .IsUnique();

                    b.ToTable("CourseBranches");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseEnrollment", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ClientId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CourseId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EarnedExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ClientId", "CourseId")
                        .IsUnique();

                    b.ToTable("CourseEnrollments");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseEnrollmentTheme", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("CourseThemeId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("EarnedExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<byte[]>("EnrollmentId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnlockedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WaitingForHomeworkAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseThemeId");

                    b.HasIndex("EnrollmentId", "CourseThemeId")
                        .IsUnique();

                    b.ToTable("CourseEnrollmentThemes");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseLevel", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CourseId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Order")
                        .IsUnique();

                    b.ToTable("CourseLevels");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseTheme", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("BranchId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("ExperiencePointsReward")
                        .HasColumnType("integer");

                    b.Property<string>("HomeworkContent")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LessonContent")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "Order")
                        .IsUnique();

                    b.ToTable("CourseThemes");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseThemeDependency", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("DependsOnThemeId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ThemeId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnThemeId");

                    b.HasIndex("ThemeId", "DependsOnThemeId")
                        .IsUnique();

                    b.ToTable("CourseThemeDependencies");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CustomTask", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("CancelledByUserId")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ClientId")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("CompletedByUserId")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("CreatedByUserId")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("DelayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("DelayedByUserId")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("DelayedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telegram")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Vk")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DelayedByUserId");

                    b.HasIndex("DelayedUntilUtc");

                    b.HasIndex("ClientId", "DueAtUtc");

                    b.ToTable("CustomTasks");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Expense", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("CategoryId")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.ExpenseCategory", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.InviteCode", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Code")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<byte[]>("RoleId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.PasswordRestorationRequest", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PasswordRestorationRequests");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Payment", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("ClientId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("ServiceId")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.RecoveryCode", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("WasUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RecoveryCodes");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.RecurrenceType", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceTypes");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 154, 87, 151, 151, 28, 28, 33, 75, 208, 49, 213, 224, 11, 188, 237 },
                            DisplayName = "Ежедневно",
                            Type = 0
                        },
                        new
                        {
                            Id = new byte[] { 1, 154, 87, 151, 195, 21, 70, 35, 134, 198, 189, 140, 186, 121, 105, 35 },
                            DisplayName = "Еженедельно",
                            Type = 1
                        },
                        new
                        {
                            Id = new byte[] { 1, 154, 87, 151, 214, 175, 143, 191, 51, 81, 199, 13, 75, 224, 208, 1 },
                            DisplayName = "Ежемесячно",
                            Type = 2
                        });
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.RecurringTaskExecution", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("AppointmentId")
                        .HasColumnType("bytea");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("CancelledByUserId")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ClientId")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("CompletedByUserId")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DelayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("DelayedByUserId")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("DelayedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("RecipientType")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RuleId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<byte[]>("TeacherId")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("DelayedByUserId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("RuleId", "Status");

                    b.HasIndex("ClientId", "RuleId", "CompletedAtUtc");

                    b.ToTable("RecurringTaskExecutions");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.RecurringTaskRule", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<int?>("CooldownDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RecurringTaskRules");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 151, 42, 51, 124, 145, 248, 218, 56, 50, 247, 8, 50, 250, 214, 128 },
                            CreatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MessageTemplate = "Здравствуйте, {Client.FirstName}! Напоминаем, что {When} в {Appointment.StartTime} у вас запланировано занятие.",
                            Name = "Напоминание о записи",
                            OffsetMinutes = 1440,
                            Type = 0,
                            UpdatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new byte[] { 1, 151, 42, 51, 176, 117, 100, 5, 171, 23, 40, 76, 250, 42, 17, 23 },
                            CooldownDays = 365,
                            CreatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MessageTemplate = "Здравствуйте, {Client.FirstName}! Поздравляем вас с днём рождения! Желаем хорошего дня, отличного настроения и вдохновения.",
                            Name = "Поздравление с днём рождения",
                            Type = 1,
                            UpdatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new byte[] { 1, 151, 42, 51, 212, 133, 109, 202, 202, 239, 232, 93, 167, 158, 71, 0 },
                            CreatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MessageTemplate = "Здравствуйте, {Client.FirstName}! Спасибо, что пришли на пробное занятие. Хотите подобрать удобное время для следующих занятий?",
                            Name = "Связаться после пробного занятия",
                            OffsetMinutes = 1440,
                            Type = 2,
                            UpdatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new byte[] { 1, 151, 42, 52, 7, 26, 3, 211, 249, 95, 79, 189, 125, 40, 160, 10 },
                            CooldownDays = 7,
                            CreatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MessageTemplate = "Здравствуйте, {Client.FirstName}! Вы давно не были на занятиях. Хотите подобрать удобное время для следующего занятия?",
                            Name = "Напомнить о занятиях",
                            Type = 3,
                            UpdatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new byte[] { 1, 151, 42, 52, 58, 169, 122, 130, 189, 13, 60, 143, 67, 219, 74, 153 },
                            CooldownDays = 1,
                            CreatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MessageTemplate = "Здравствуйте, {Teacher.FirstName}! Отправляем ваше расписание на {Date}.",
                            Name = "Отправить расписание преподавателю",
                            Type = 4,
                            UpdatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new byte[] { 1, 151, 68, 39, 35, 32, 242, 46, 90, 222, 158, 36, 71, 1, 68, 170 },
                            CreatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MessageTemplate = "Здравствуйте, {Client.FirstName}! Напоминаем, что у вас есть задолженность. Напишите нам, пожалуйста, если хотите уточнить сумму или подобрать удобный способ оплаты.",
                            Name = "Напомнить о долге через день",
                            OffsetMinutes = 1440,
                            Type = 5,
                            UpdatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new byte[] { 1, 151, 68, 39, 35, 32, 242, 46, 90, 222, 158, 36, 71, 1, 68, 171 },
                            CreatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MessageTemplate = "Здравствуйте, {Client.FirstName}! Напоминаем о задолженности по занятиям. Если удобно, можем помочь с оплатой или ответить на вопросы.",
                            Name = "Напомнить о долге через 3 дня",
                            OffsetMinutes = 4320,
                            Type = 5,
                            UpdatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new byte[] { 1, 151, 68, 39, 35, 32, 242, 46, 90, 222, 158, 36, 71, 1, 68, 172 },
                            CreatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MessageTemplate = "Здравствуйте, {Client.FirstName}! У вас по-прежнему есть задолженность. Напишите нам, если нужна помощь с оплатой или хотите обсудить детали.",
                            Name = "Напомнить о долге через неделю",
                            OffsetMinutes = 10080,
                            Type = 5,
                            UpdatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new byte[] { 1, 151, 68, 39, 35, 32, 242, 46, 90, 222, 158, 36, 71, 1, 68, 173 },
                            CooldownDays = 7,
                            CreatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            MessageTemplate = "Здравствуйте, {Client.FirstName}! Напоминаем, что задолженность всё ещё не закрыта. Если нужна помощь или удобный вариант оплаты, мы на связи.",
                            Name = "Напоминать о долге каждую неделю",
                            OffsetMinutes = 10080,
                            Type = 5,
                            UpdatedAtUtc = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.RequestReplay", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReplayKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("ResponseEntityId")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint", "ReplayKey")
                        .IsUnique();

                    b.ToTable("RequestReplays");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Role", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 1, 153, 237, 189, 136, 239, 85, 185, 220, 69, 200, 138, 71, 160, 55, 244 },
                            DisplayName = "Суперпользователь",
                            RoleName = 1
                        },
                        new
                        {
                            Id = new byte[] { 1, 153, 237, 189, 164, 92, 201, 142, 60, 167, 216, 236, 125, 205, 69, 213 },
                            DisplayName = "Администратор",
                            RoleName = 2
                        },
                        new
                        {
                            Id = new byte[] { 1, 153, 237, 189, 179, 9, 105, 35, 34, 182, 33, 139, 189, 171, 222, 9 },
                            DisplayName = "Пользователь",
                            RoleName = 4
                        },
                        new
                        {
                            Id = new byte[] { 1, 151, 239, 169, 226, 242, 184, 185, 113, 187, 195, 178, 83, 143, 72, 233 },
                            DisplayName = "Клиент",
                            RoleName = 8
                        });
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Service", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.ServicePrice", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("ServiceId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServicePriceHistory");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Session", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasRevoked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ClientId")
                        .HasColumnType("bytea");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailBlindIndex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<byte[]>("RoleId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Telegram")
                        .HasColumnType("text");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("text");

                    b.Property<string>("Vk")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("\"ClientId\" IS NOT NULL");

                    b.HasIndex("EmailBlindIndex")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.UserOnboardingState", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserOnboardingStates");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.UserVacation", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserVacations");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.UserWorkingHoursDay", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("EndMinuteOfDay")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("boolean");

                    b.Property<int>("StartMinuteOfDay")
                        .HasColumnType("integer");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("UserWorkingHoursDays");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Appointment", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelodyTrack.Backend.Data.Models.CourseTheme", "CourseTheme")
                        .WithMany()
                        .HasForeignKey("CourseThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId");

                    b.HasOne("MelodyTrack.Backend.Data.Models.AppointmentRecurrenceRule", "RecurringRule")
                        .WithMany()
                        .HasForeignKey("RecurringRuleId");

                    b.HasOne("MelodyTrack.Backend.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CourseTheme");

                    b.Navigation("Provider");

                    b.Navigation("RecurringRule");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.AppointmentRecurrenceRule", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId");

                    b.HasOne("MelodyTrack.Backend.Data.Models.RecurrenceType", "RecurrenceType")
                        .WithMany()
                        .HasForeignKey("RecurrenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelodyTrack.Backend.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Provider");

                    b.Navigation("RecurrenceType");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Client", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.ClientContacts", "Contacts")
                        .WithMany()
                        .HasForeignKey("ContactsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelodyTrack.Backend.Data.Models.ClientSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contacts");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.ClientPortalLoginLink", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseBlock", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Course", "Course")
                        .WithMany("Blocks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseBranch", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.CourseBlock", "Block")
                        .WithMany("Branches")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseEnrollment", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelodyTrack.Backend.Data.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseEnrollmentTheme", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.CourseTheme", "CourseTheme")
                        .WithMany()
                        .HasForeignKey("CourseThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelodyTrack.Backend.Data.Models.CourseEnrollment", "Enrollment")
                        .WithMany("Themes")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseTheme");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseLevel", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Course", "Course")
                        .WithMany("Levels")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseTheme", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.CourseBranch", "Branch")
                        .WithMany("Themes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseThemeDependency", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.CourseTheme", "DependsOnTheme")
                        .WithMany("RequiredForThemes")
                        .HasForeignKey("DependsOnThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MelodyTrack.Backend.Data.Models.CourseTheme", "Theme")
                        .WithMany("Dependencies")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnTheme");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CustomTask", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "DelayedByUser")
                        .WithMany()
                        .HasForeignKey("DelayedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CancelledByUser");

                    b.Navigation("Client");

                    b.Navigation("CompletedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DelayedByUser");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Expense", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.InviteCode", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Payment", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelodyTrack.Backend.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.Navigation("Client");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.RecoveryCode", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.RecurringTaskExecution", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "DelayedByUser")
                        .WithMany()
                        .HasForeignKey("DelayedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.RecurringTaskRule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Appointment");

                    b.Navigation("CancelledByUser");

                    b.Navigation("Client");

                    b.Navigation("CompletedByUser");

                    b.Navigation("DelayedByUser");

                    b.Navigation("Rule");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.ServicePrice", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Session", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.User", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MelodyTrack.Backend.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.UserOnboardingState", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "User")
                        .WithOne("OnboardingState")
                        .HasForeignKey("MelodyTrack.Backend.Data.Models.UserOnboardingState", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.UserVacation", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "User")
                        .WithMany("Vacations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.UserWorkingHoursDay", b =>
                {
                    b.HasOne("MelodyTrack.Backend.Data.Models.User", "User")
                        .WithMany("WorkingHours")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.Course", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Levels");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseBlock", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseBranch", b =>
                {
                    b.Navigation("Themes");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseEnrollment", b =>
                {
                    b.Navigation("Themes");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.CourseTheme", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("RequiredForThemes");
                });

            modelBuilder.Entity("MelodyTrack.Backend.Data.Models.User", b =>
                {
                    b.Navigation("OnboardingState");

                    b.Navigation("Vacations");

                    b.Navigation("WorkingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
